name: testing
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipython
  - pandas>=1.3.0
  - numpy>=1.21.0
  - nltk>=3.6.7
  - scikit-learn>=1.0.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - jupyterlab>=3.0.0
  - jupyterlab-git>=0.32.0
  - jupyterlab_code_formatter>=1.4.11
  - pip
  - pip:
    - pytest
    - pylint
    - pytest-cov
